spring:
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    #开发禁用缓存
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/ssmdb?characterEncoding=UTF-8&useSSL=false
    username: root
    password: ml763829015
     # 可省略驱动配置, sprin-boot 会由url检测出驱动类型
     # driver-class-name: com.mysql.jdbc.Driver
    hikari:
        connection-timeout: 60000
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.boot.domain
  # spring-boot默认打印输出info级别以上的，可在此处修改输出级别
  logging:
    level:
      root: info